// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tiendaRopaEagleDecv.Data;

public partial class Categorias
{
    public int IdCategoria { get; set; }

    public string Nombre { get; set; }

    public int? IdCategoriaPadre { get; set; }

    public virtual Categorias IdCategoriaPadreNavigation { get; set; }

    public virtual ICollection<Categorias> InverseIdCategoriaPadreNavigation { get; set; } = new List<Categorias>();

    public virtual ICollection<Productos> Productos { get; set; } = new List<Productos>();
}