// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tiendaRopaEagleDecv.Data;

public partial class Productos
{
    public int IdProducto { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public decimal? Precio { get; set; }

    public string Marca { get; set; }

    public string ImagenUrl { get; set; }

    public int? IdCategoria { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual Categorias IdCategoriaNavigation { get; set; }

    public virtual ICollection<Inventario> Inventario { get; set; } = new List<Inventario>();

    public virtual ICollection<ProductoColores> ProductoColores { get; set; } = new List<ProductoColores>();

    public virtual ICollection<ProductoTallas> ProductoTallas { get; set; } = new List<ProductoTallas>();
}