// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tiendaRopaEagleDecv.Data;

public partial class ProductoColores
{
    public int IdProductoColor { get; set; }

    public int? IdProducto { get; set; }

    public string Color { get; set; }

    public virtual Productos IdProductoNavigation { get; set; }
}