// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace tiendaRopaEagleDecv.Data;

public partial class ProductoTallas
{
    public int IdProductoTalla { get; set; }

    public int? IdProducto { get; set; }

    public string Talla { get; set; }

    public virtual Productos IdProductoNavigation { get; set; }
}